// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mintersdk

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4552731bDecodeGithubComValidatorCenterMinterGoSdkNode(in *jlexer.Lexer, out *node_estimate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "jsonrpc":
			out.JSONRPC = string(in.String())
		case "id":
			out.ID = string(in.String())
		case "result":
			(out.Result).UnmarshalEasyJSON(in)
		case "error":
			(out.Error).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4552731bEncodeGithubComValidatorCenterMinterGoSdkNode(out *jwriter.Writer, in node_estimate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"jsonrpc\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.JSONRPC))
	}
	{
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"result\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Result).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"error\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Error).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v node_estimate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4552731bEncodeGithubComValidatorCenterMinterGoSdkNode(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v node_estimate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4552731bEncodeGithubComValidatorCenterMinterGoSdkNode(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *node_estimate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4552731bDecodeGithubComValidatorCenterMinterGoSdkNode(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *node_estimate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4552731bDecodeGithubComValidatorCenterMinterGoSdkNode(l, v)
}
func easyjson4552731bDecodeGithubComValidatorCenterMinterGoSdk(in *jlexer.Lexer, out *_estimateResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "will_pay":
			out.WillPay = string(in.String())
		case "will_get":
			out.WillGet = string(in.String())
		case "commission":
			out.Commission = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4552731bEncodeGithubComValidatorCenterMinterGoSdk(out *jwriter.Writer, in _estimateResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"will_pay\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.WillPay))
	}
	{
		const prefix string = ",\"will_get\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.WillGet))
	}
	{
		const prefix string = ",\"commission\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Commission))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v _estimateResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4552731bEncodeGithubComValidatorCenterMinterGoSdk(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v _estimateResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4552731bEncodeGithubComValidatorCenterMinterGoSdk(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *_estimateResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4552731bDecodeGithubComValidatorCenterMinterGoSdk(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *_estimateResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4552731bDecodeGithubComValidatorCenterMinterGoSdk(l, v)
}
func easyjson4552731bDecodeGithubComValidatorCenterMinterGoSdk1(in *jlexer.Lexer, out *EstimateResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "will_pay":
			out.WillPay = float32(in.Float32())
		case "will_get":
			out.WillGet = float32(in.Float32())
		case "commission":
			out.Commission = float32(in.Float32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4552731bEncodeGithubComValidatorCenterMinterGoSdk1(out *jwriter.Writer, in EstimateResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"will_pay\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float32(float32(in.WillPay))
	}
	{
		const prefix string = ",\"will_get\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float32(float32(in.WillGet))
	}
	{
		const prefix string = ",\"commission\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float32(float32(in.Commission))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EstimateResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4552731bEncodeGithubComValidatorCenterMinterGoSdk1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EstimateResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4552731bEncodeGithubComValidatorCenterMinterGoSdk1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EstimateResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4552731bDecodeGithubComValidatorCenterMinterGoSdk1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EstimateResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4552731bDecodeGithubComValidatorCenterMinterGoSdk1(l, v)
}
